---
- name: Install Python3 using raw module
  become: yes
  block:
    - name: Install Python3 on CentOS
      raw: yum install -y python3
      args:
        executable: /bin/sh
      when: ansible_os_family == "RedHat"  # Для CentOS

    - name: Install Python3 on Ubuntu
      raw: apt update && apt install -y python3
      args:
        executable: /bin/sh
      when: ansible_os_family == "Debian"  # Для Ubuntu

- name: Gather facts after installing Python
  setup:  # Собираем факты после установки Python